<script>
import pawpaw from "./assets/pawpaw.gif"
</script>

<div class="p-4">
<article class="prose m-auto">
<h1>About Gamebook Webby Press</h1>
<p>
	This is a minimal web app to help you create gamebooks for the <a href="https://play.date" target="_blank">Playdate</a> handheld console by <a href="https://panic.com" target="_blank">Panic</a>. The source-code generated by <i>Gamebook.Webby.Press</i> is compatible with the <a href="https://play.date/dev/" target="_blank">Playdate SDK</a> and can be compiled out-of-the-box if you have everything set correctly on your machine.
</p>
<figure>
	<img src="{pawpaw}">
</figure>
<p>
	<b>Your data never leaves your computer.</b> This is a pure client-side webapp, all data is loaded in your browser, there is no backend. This means that I don't have access to the book you're writing, which also means that you're responsible to use the <i>Save/Load</i> features to backup your gamebook to disk. GWP tries it best to always save your gamebooks to local storage. Saving to disk is a good practice to keep your books safe.
</p>

</article>
</div>